table 'olist_analytics_gold dim_date'
	lineageTag: 3b53048e-395d-41e5-ae8d-95040ff1728c
	dataCategory: Time

	column date_key
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 607544ca-55a5-49d4-b741-f57b0a90c203
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: c997ad00-dc3e-4668-a771-55dd7345dcef
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		formatString: 0
		lineageTag: 3e35d49c-c71a-43e1-a9b7-ad6667f9799d
		summarizeBy: sum
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column month_number
		dataType: int64
		formatString: 0
		lineageTag: 531cc1bf-7046-4059-9b14-1d19d27dd684
		summarizeBy: sum
		sourceColumn: month_number

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		lineageTag: 6efbdf07-e889-4c5b-8823-fbff2d0e772b
		summarizeBy: none
		sourceColumn: month_name
		sortByColumn: month_number

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column week_number
		dataType: int64
		formatString: 0
		lineageTag: eecafb86-7d29-4626-8268-f0d1c847d95f
		summarizeBy: sum
		sourceColumn: week_number

		annotation SummarizationSetBy = Automatic

	column day_of_month
		dataType: int64
		formatString: 0
		lineageTag: e92dc622-b93c-40f2-8e69-e175d6c7be86
		summarizeBy: sum
		sourceColumn: day_of_month

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		formatString: 0
		lineageTag: eadf04f4-9e86-4e00-a0be-1f15ad7adbe3
		summarizeBy: sum
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		lineageTag: 9a4a9bf9-9d69-4c0c-b3ac-bce631d94465
		summarizeBy: none
		sourceColumn: day_name
		sortByColumn: day_of_week

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c60b98cb-3d17-4a42-a5ed-5e32e1a8c391
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column 'Year Month' = FORMAT([date_key], "YYYY-MM")
		lineageTag: 9175a75e-705f-489e-a3ba-2a99fc02c598
		summarizeBy: none
		sortByColumn: 'Year Month Sort'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Year Month Sort' = YEAR([date_key]) * 100 + MONTH([date_key])
		formatString: 0
		lineageTag: e08c81ee-422f-4267-b7e7-a322c48ac7d3
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Month Start' =
			
			DATE(
			    YEAR('olist_analytics_gold dim_date'[date_key]),
			    MONTH('olist_analytics_gold dim_date'[date_key]),
			    1)
		formatString: General Date
		lineageTag: 7fb5f33f-3e85-4ec9-90c1-fc46f3f8b2b0
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	hierarchy 'Date Hierarchy'
		lineageTag: dddb362c-9971-4141-916b-1447f908d98e

		level Year
			lineageTag: a8889ae3-0439-473d-888d-0a6d6d8f96c5
			column: Year

		level quarter
			lineageTag: 1d1c900f-bc97-4c5e-8ae1-da503dcac6a1
			column: quarter

		level month_name
			lineageTag: 5fb426d4-a695-4d10-9d0d-501cee00c475
			column: month_name

		level date_key
			lineageTag: 6ff54a6a-cebf-4c1a-9139-1d2306f5c57c
			column: date_key

	partition 'olist_analytics_gold dim_date' = m
		mode: import
		source =
				let
				  Source = PostgreSQL.Database("localhost:5432", "olist_analytics"),
				  #"Navigation 1" = Source{[Schema = "olist_analytics_gold", Item = "dim_date"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(#"Navigation 1",{{"year", Int64.Type}, {"quarter", Int64.Type}, {"month_number", Int64.Type}, {"week_number", Int64.Type}, {"day_of_month", Int64.Type}, {"day_of_week", Int64.Type}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"year", "Year"}})
				in
				  #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

